CREATE TABLE Employee
(
Em_id CHAR(5),
Em_name NVARCHAR(10) NOT NULL,
Em_dop  NVARCHAR(10) NULL,
PRIMARY KEY(Em_id)
)
CREATE TABLE Product
(
P_id CHAR(5),
P_name NVARCHAR(10) NOT NULL,
Price INT,
PRIMARY KEY(P_id)
)
CREATE TABLE sales
(
Em_id CHAR(5),
P_id CHAR(5),
PRIMARY KEY(P_id,Em_id),
FOREIGN KEY(Em_id) REFERENCES Employee(Em_id)
ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(P_id) REFERENCES Product(P_id)
ON UPDATE CASCADE ON DELETE CASCADE,
)