CREATE TABLE Department--1
(
Dep_Id CHAR(5),
Dep_name NVARCHAR(10)NOT NULL,
Dep_teacher NVARCHAR(10)NOT NULL,
PRIMARY KEY(Dep_id)
)
CREATE TABLE Teacher--1
(
Teacher_Id CHAR(5),
Teacher_name NVARCHAR(10)NOT NULL,
PRIMARY KEY(Teacher_id)
)
CREATE TABLE Student--2
(
Stu_Id CHAR(5),
Stu_name NVARCHAR(10)NOT NULL,
Grade CHAR(1)NOT NULL,
Dep_id CHAR(5)NOT NULL,
PRIMARY KEY(Stu_id),
FOREIGN KEY(Dep_id) REFERENCES Department(Dep_id)
ON UPDATE CASCADE ON DELETE CASCADE,
)
CREATE TABLE Class--2
(
Class_Id CHAR(5),
Class_name NVARCHAR(10)NOT NULL,
Credit INT NOT NULL,
Teacher_id CHAR(5)NOT NULL,
PRIMARY KEY(Class_id),
FOREIGN KEY(Teacher_id) REFERENCES Teacher(Teacher_id)
ON UPDATE CASCADE ON DELETE CASCADE,
)
CREATE TABLE Score--3
(
Stu_Id CHAR(5),
Class_Id CHAR(5),
Score INT NOT NULL,
PRIMARY KEY(Stu_id,Class_id),
FOREIGN KEY(Stu_id) REFERENCES Student(Stu_id)
ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(Class_id) REFERENCES Class(Class_id)
ON UPDATE CASCADE ON DELETE CASCADE,
)
