CREATE TABLE Customer--1
(
Cus_id CHAR(5),
Cus_name NVARCHAR(10) NOT NULL,
Cus_phone NVARCHAR(10),
Cus_fax NVARCHAR(10),
PRIMARY KEY(Cus_id)
)
CREATE TABLE Product--1
(
P_id CHAR(5),
P_name NVARCHAR(10) NOT NULL,
Price INT,
PRIMARY KEY(P_id)
)
CREATE TABLE Order_whole--2
(
O_id CHAR(5),
O_date NVARCHAR(10) NOT NULL,
Cus_id CHAR(5),
PRIMARY KEY(O_id),
FOREIGN KEY(Cus_id) REFERENCES Customer(Cus_id)
ON UPDATE CASCADE ON DELETE CASCADE,
)
CREATE TABLE Order_detail--3
(
O_id CHAR(5),
P_id CHAR(5),
Number INT NOT NULL,
PRIMARY KEY(O_id,P_id),
FOREIGN KEY(O_id) REFERENCES Order_whole(O_id)
ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(P_id) REFERENCES Product(P_id)
ON UPDATE CASCADE ON DELETE CASCADE,
)